# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: ì´í˜ì£¼
title: ì´ë ¥ì„œ
email: leehyeokju1@gmail.com
# email_title: Email (Email title override)
phone: 010-5842-2831
# phone_title: Phone (Phone title override)
website: http://í˜ì£¼.kro.kr
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ihyeogju17
github_username:  fada2020
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: "100079903582838"
# flickr_username: jekyll
instagram_username: hyeogjui38
linkedin_username: ju-hyeok-48750b193
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/simpson.jpg
about_content: | # this will include new lines to allow paragraphs
  í¬íŠ¸í´ë¦¬ì˜¤ëŠ” ì´ê³³ì„ ì°¸ê³ í•´ ì£¼ì„¸ìš”. [links](http://xn--o55b31v.kro.kr/)

  language ðŸ”­

  ![alt text](https://img.shields.io/badge/OpenJDK-black?style=for-the-badge&logo=OpenJDK&logoColor=white "OpenJDK")
  ![alt text](https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=JavaScript&logoColor=white "Python")
  ![alt text](https://img.shields.io/badge/Gradle-02303A?style=for-the-badge&logo=Gradle&logoColor=white "Gradle")

  database ðŸŽˆ

  ![alt text](https://img.shields.io/badge/MariaDB-003545?style=for-the-badge&logo=MariaDB&logoColor=white "MariaDB")
  ![alt text](https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=MySQL&logoColor=white "MySQL")
  ![alt text](https://img.shields.io/badge/PostgreSQL-4169E1?style=for-the-badge&logo=PostgreSQL&logoColor=white "PostgreSQL")

  framework âœ¨

  ![alt text](https://img.shields.io/badge/thymeleaf-005F0F?style=for-the-badge&logo=thymeleaf&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Vite-646CFF?style=for-the-badge&logo=Vite&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Spring Boot-6DB33F?style=for-the-badge&logo=SpringBoot&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/docker-2496ED?style=for-the-badge&logo=docker&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Svelte-FF3E00?style=for-the-badge&logo=Svelte&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Hibernate JPA-59666C?style=for-the-badge&logo=Hibernate&logoColor=white "object")

  tool ðŸŽ‰

  ![alt text](https://img.shields.io/badge/Git-F05032?style=for-the-badge&logo=Git&logoColor=white "object") 
  ![alt text](https://img.shields.io/badge/GitHub Actions-2088FF?style=for-the-badge&logo=GitHubActions&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/IntelliJ IDEA-000000?style=for-the-badge&logo=IntelliJIDEA&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Visual Studio Code-007ACC?style=for-the-badge&logo=VisualStudioCode&logoColor=white "object")

  os ðŸŽ

  ![alt text](https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=Linux&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/CentOS-262577?style=for-the-badge&logo=CentOS&logoColor=white "object")

  library ðŸ–¼

  ![alt text](https://img.shields.io/badge/jquery-0769AD?style=for-the-badge&logo=jquery&logoColor=white "object")

  cloud ðŸŽ´

  ![alt text](https://img.shields.io/badge/Oracle cloud-F80000?style=for-the-badge&logo=Oracle&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/Amazon EC2-FF9900?style=for-the-badge&logo=AmazonEC2&logoColor=white "object")

  etc ðŸ§§

  ![alt text](https://img.shields.io/badge/html5-E34F26?style=for-the-badge&logo=html5&logoColor=white "object")
  ![alt text](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=CSS3&logoColor=white "object")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: hibricks converting
        link: [hibricks](https://hibricks.com)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        title: ebricks renewal
        link: [ebricks](https://ebricks.co.kr)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*
# Footer
footer_show_references: true
# references_title: References on request (Override references text)
# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag
exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
